services:
  backend:
    build:
      context: ./BackEnd/API
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./BackEnd/API:/API
  postgres:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data: