[project]
name = "gtr-task2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "firecrawl-py>=4.5.0",
    "rich>=14.2.0",
]
